title: Richard Anciado # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Coding. Trading. Simplicity. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
